name: Terrascan CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    #Step 2: Set up Node.js environment and install dependencies
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install

    # Step 3: Install Terrascan
    - name: Install Terrascan
      run: |
       curl -L https://github.com/tenable/terrascan/releases/download/v1.17.0/terrascan_1.17.0_Linux_x86_64.tar.gz -o terrascan.tar.gz
       tar -xvzf terrascan.tar.gz
       sudo mv terrascan /usr/local/bin/terrascan
       terrascan version   
    - name: Run Terrascan TypeScript Script
      #run: npx ts-node ./terrascan.ts
      run: npx tsc
    - name: compile
      #run: node ./terrascan.js
      run: npx ts-node ./terrascan.ts


