name: Run Terrascan

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Terrascan
        run: npm install -g terrascan

      - name: Run Terrascan
        run: terrascan scan -t aws -f .

      - name: Upload Terrascan results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: terrascan-results
          path: terrascan-report.json
