name: Terrascan Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Terrascan
      - name: Install Terrascan
        run: |
          curl -L https://github.com/accurics/terrascan/releases/latest/download/terrascan_linux_amd64.tar.gz -o terrascan.tar.gz
          tar -xvf terrascan.tar.gz terrascan
          sudo mv terrascan /usr/local/bin/

      # Run Terrascan scan
      - name: Run Terrascan
        run: |
          terrascan scan --iac ./ .  # Adjust the directory based on where your IaC files are located

      # Upload Terrascan scan results as an artifact
      - name: Upload Terrascan results
        uses: actions/upload-artifact@v3
        with:
          name: terrascan-report
          path: terrascan-output.json
