name: Terrascan Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terrascan:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Terrascan
      - name: Install Terrascan
        run: |
         curl -L https://github.com/tenable/terrascan/releases/download/v1.17.0/terrascan_1.17.0_Linux_x86_64.tar.gz -o terrascan.tar.gz
         tar -xvzf terrascan.tar.gz
         sudo mv terrascan /usr/local/bin/terrascan
         terrascan version
      # Run Terrascan scan
      - name: Run Terrascan
        run: | 
          terrascan scan -d ./terraform/backend.tf --iac-type terraform 
  # Adjust the directory based on where your IaC files are locat

      # Upload Terrascan scan results as an artifact
      - name: Upload Terrascan results
        uses: actions/upload-artifact@v3
        with:
          name: terrascan-report
          path: terrascan-output.json
